<?php
	$mainMenu = array(
		array('href' => 'the-joker', 'title' => 'The Joker', 'active' => true),
		array('href' => 'the-penguin', 'title' => 'The Penguin', 'active' => true),
		array('href' => 'the-riddler', 'title' => 'The Riddler', 'active' => true),
		array('href' => 'mr-freeze', 'title' => 'Mr. Freeze', 'active' => true),
		array('href' => 'the-scarecrow', 'title' => 'The Scarecrow', 'active' => true),
		array('href' => 'poison-ivy', 'title' => 'Poison Ivy', 'active' => true),
		array('href' => 'ras-al-ghul', 'title' => 'Ra\'s al Ghul', 'active' => true),
		array('href' => 'bane', 'title' => 'Bane', 'active' => false)
	);

	$pages = array(
		'the-joker' => ['title' => 'The Joker', 'imgcover' => 'images/Doomsday_Clock_Vol_1_5_Textless_Variant.jpg" alt="The Joker', 'backstory' => "<h1>The Joker</h1> <p>The Joker is a supervillain and the archenemy of Batman. He was first introduced in Batman #1 (Spring 1940) and has remained consistently popular. The Joker is a master criminal with a clown-like appearance, and is considered one of the most infamous criminals within Gotham City. Initially portrayed as a violent sociopath who murders people for his own amusement, the Joker later in the 1940s began to be written as a goofy trickster-thief. That characterization continued through the late-1950s and 1960s before the character became again depicted as a vicious, calculating, psychopathic killer. The Joker has been responsible for numerous tragedies in Batman's life, including the paralysis of Barbara Gordon (Batgirl/Oracle) and the murders of Jason Todd (the second Robin) and Jim Gordon's second wife Sarah Essen.</p>", 'imgactor' => 'images/the-dark-knight.jpg" alt="The Joker', 'active' => true],
		'the-penguin' => ['title' => 'The Penguin', 'imgcover' => 'images/Penguin_new_52.jpg" alt="The Penguin', 'backstory' => "<h1>The Penguin</h1> <p>The Penguin (Oswald Chesterfield Cobblepot) is a DC Comics supervillain and an enemy of Batman. He was introduced by artist Bob Kane and writer Bill Finger, he first appeared in Detective Comics #58 (December 1941).</p> <p>The Penguin, one of Batman's oldest foes, is an eccentric criminal mastermind, known as much for his love of ornithology and trick umbrellas as for his already shady business dealings. Gotham City's popular Iceberg Lounge serves as Penguin's front for a number of illegal financial stature; the Penguin is a wily foe whose umbrellas conceal a variety of deadly weapons and gadgets.</p> <p>In most incarnations, the Penguin is a short, chubby (though he wasn't really fat in the original Batman series) man who wears a tuxedo, top hat, monocle, white gloves (black in Batman Returns), and spats. A mobster-type criminal, he fancies himself a 'gentleman of crime'. Unlike most Batman villains, he is sane and doesn't theme his crimes around a psychotic obsession; his intelligence and aristocratic personality starkly contrast against demented Batman villains, such as The Joker.</p>", 'imgactor' => 'images/batman-returns.jpg" alt="The Penguin', 'active' => true],
		'the-riddler' => ['title' => 'The Riddler', 'imgcover' => 'images/6462105-batman_vol_3_27_textless.jpg" alt="The Riddler', 'backstory' => "<h1>The Riddler</h1> <p>The Riddler, (Edward 'E.' Nigma, also spelled Nygma by some writers), is an enemy of Batman. Created by writer Bill Finger and artist Dick Sprang, he first appeared in Detective Comics #140 (October 1948).</p> <p>Known for his purple domino mask and green question mark-covered costume, either as a skintight cat suit or a business suit and bowler hat and his special question mark shaped cane, the Riddler is obsessed with riddles, puzzles, and word games. He delights in forewarning police and Batman of his capers by sending them complex clues.</p> <p>Like most Batman villains, the Riddler has become a darker, more three-dimensional character in recent years. Whereas he was once portrayed as a playful but sane criminal trickster, he is now the victim of an intense obsessive compulsion.</p>", 'imgactor' => 'images/jim-carrey.jpg" alt="The Riddler', 'active' => true],
		'mr-freeze' => ['title' => 'Mr. Freeze', 'imgcover' => 'images/2361007-batman_annual_02_1000.jpg" alt="Mr. Freeze', 'backstory' => "<h1>Mr. Freeze</h1> <p>Mr Freeze first appeared in Batman #121 (February, 1959) and was created by Bob Kane, David Wood and Sheldon Moldoff as 'Mr Zero' and was considered a gimmick character. He was later renamed and popularized by the 1960s Batman television series, in which he was played by several actors.</p> <p>Nearly 30 years later, a television adaptation of Batman revitalized him once again. Batman: The Animated Series retold Mr. Freeze's origin in 'Heart of Ice', an episode by writer Paul Dini. The episode introduced his terminally ill, cryogenically frozen wife Nora, which explained his obsession with ice and need to build a criminal empire to raise research funds. This more complex, tragic character was enthusiastically accepted by fans, and has become the standard portrayal for the character in most forms of media, including the comic book series itself, which previously had the character casually killed off by the Joker. Freeze was resurrected in the comic after the episode aired.</p>", 'imgactor' => 'images/mr.freeze.jpg" alt="Mr. Freeze', 'active' => true],
		'the-scarecrow' => ['title' => 'The Scarecrow', 'imgcover' => 'images/Scarecrow_new_52.jpg" alt="The Scarecrow', 'backstory' => "<h1>The Scarecrow</h1> <p>Dr. Jonathan Crane, also known as The Scarecrow, is a DC Comics supervillain and an enemy of Batman. Created by Batman creators Bill Finger and Bob Kane, he first appeared in World's Finest Comics #3 (Fall 1941). His scarecrow costume, lanky appearance and surname were inspired by Ichabod Crane of the horror fable 'The Legend of Sleepy Hollow'.</p> The Scarecrow is an overly-obsessive and deranged ex-professor of psychology who uses a variety of drugs and psychological tactics to use the fears and phobias of his adversaries. He does not commit his crimes for wealth, but rather as a form of 'research' to further study the effects of fear on humans (later, he does it to satisfy his own psychopathic desires), making the innocent citizens of Gotham his unwilling guinea pigs.</p>", 'imgactor' => 'images/scarecrow.jpg" alt="The Scarecrow', 'active' => true],
		'poison-ivy' => ['title' => 'Poison Ivy', 'imgcover' => 'images/5939265-1499257220009.jpg" alt="Poison Ivy', 'backstory' => "<h1>Poison Ivy</h1> <p>Poison Ivy is an enemy of Batman. She is depicted as one of the world's most prominent eco-terrorists. She is obsessed with plants, botany, and environmentalism. She uses toxins from plants and her own bloodstream for her criminal activities, which are usually aimed at protecting the natural environment. She creates love potions that ensnare Batman, Superman, and other strong-willed individuals. Fellow villain Harley Quinn is her recurring partner-in-crime and possibly her only human friend.</p> <p>The dangerous experiments placed a deliberate overdose of plant and animal based toxins into her blood stream that make her touch deadly and allowed her to boost her immunity to all poisons, viruses, bacteria, and fungi. This immunity also includes Joker venom. Some comics have even gone so far as to depict her as more plant than human, breathing CO2 and requiring sunlight to survive.</p> <p>Ivy is known to be able to seduce men and women alike, often using pheromones to do so; she is even able to use these to control Superman, although she requires kryptonite for them to work. She specializes in hybrids and can create the most potently powerful toxins in Gotham City. Often these toxins are secreted from her lips and administered via a kiss. They come in a number of varieties, from mind-controlling drugs to instantly fatal narcotics.</p>", 'imgactor' => 'images/uma-thurman.jpg" alt="Poison Ivy', 'active' => true],
		'ras-al-ghul' => ['title' => 'Ra\'s al Ghul', 'imgcover' => 'images/Ra\'s_al_Ghul-1.jpg" alt="Ras al Ghul', 'backstory' => "<h1>Ra's al Ghul</h1> <p>Ra's al Ghul, sometimes written Rā's al Ghūl, is a DC Comics supervillain and an enemy of Batman. His name is Arabic for \"head of the demon\". Created by writer Dennis O'Neil and artist Neal Adams, he was introduced in Batman #232's 'Daughter of the Demon' (June 1971). He has also come into conflict with Superman and other DC Comics superheroes.</p> <p>Little is known of the early years of the nearly immortal Ra's, but it is accepted that he has lived for many centuries due to the Lazarus Pits' mysterious brews that restore his youth. A brilliant master of strategy and organization, Ra's al Ghul's goal is to save the Earth from ecological devastation by destroying most of its population. He recognizes Batman as both a worthy foe and a possible ally—except that Batman cannot accept his dystopian worldview. Batman also shares a love-hate relatio</p>", 'imgactor' => 'images/siddig.jpg" alt="Ra\'s al Ghul', 'active' => true],
		'bane' => ['title' => 'Bane', 'imgcover' => 'images/Batman_The_Dark_Knight_Vol_2-6_Cover-1_Teaser.jpg" alt="Bane', 'backstory' => "<h1>Bane</h1> <p>Bane is an escaped convict from an island prison in South America and a super-villain/assassin. Bane has abnormal physical strength as a result of having undergone experiments involving a derivative of the drug Venom. He became known as \"The Man Who Broke the Bat\" when he broke Batman's back, forcing Bruce Wayne to give up the Batman persona while he recuperated. Bane was originally created by writers Chuck Dixon and Doug Moench and artist, Graham Nolan, from a concept by Denny O'Neil. He first appeared in Batman: Vengeance of Bane #1 (January 1993).</p> <p>Originally intended as a \"dark mirror\" of the highly disciplined and multi-skilled pulp hero Doc Savage, Bane spends his childhood in the hellish prison of Pena Duro on the corrupt South American island nation of Santa Prisca. He develops super strength through a forced experiment involving the drug Venom. Although his dependency on Venom is an immense weakness, Bane has been one of Batman's most intelligent and physically powerful foes. He is best known for breaking Batman's back in the \"Knightfall\" story arc.</p> <p>Although primarily a villain, Bane is a complex character and has worked to take down drug lords. Despite their history, he has sometimes had Batman's financial backing and direct assistance.</p>", 'imgactor' => 'images/bane.jpg" alt="Bane', 'active' => true]
	);

	$title = '';
	$imgCover = '';
	$backstory = '';
	$imgActor = '';

	$data = $pages[$currentPage];
	// print_r($data);

	$name = basename($_SERVER['SCRIPT_NAME']);
	$navMenu = '';

	foreach ($mainMenu as $menuItem){
		if($menuItem['active'] === true) {
			$class = $pages == $menuItem['href'] ? 'class="current"' : "";

			$navMenu .= '<li ><a href="index.php?page='.$menuItem['href'].'" target="_self" '.$class.'> ' .$menuItem['title'].'</a></li>';
		}
	};
	if($data['active'] === true) {
		$title = $data['title'];
		$imgCover = $data['imgcover'];
		$backstory = $data['backstory'];
		$imgActor = $data['imgactor'];
	};
?>